name: Python CI

on:
  push:
    branches: [ main ]
    paths:
      - 'pytest-pybia/**'
      - '.github/workflows/python.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'pytest-pybia/**'
      - '.github/workflows/python.yml'

jobs:
  test:
    name: Test Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov
          cd pytest-pybia
          pip install -e .
      
      - name: Run tests
        run: |
          cd pytest-pybia
          python -m pytest --cov=pytest_pybia
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./pytest-pybia/coverage.xml
          fail_ci_if_error: false
  
  lint:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 black isort
      
      - name: Check formatting with Black
        run: |
          cd pytest-pybia
          black --check .
      
      - name: Check imports with isort
        run: |
          cd pytest-pybia
          isort --check .
      
      - name: Lint with flake8
        run: |
          cd pytest-pybia
          flake8 . 